horaPartida = int(input("Ingrese hora de partida  "))
minutoPartida = int(input("Ingrese minuto de partida  "))
segundoPartida = int(input("Ingrese segundo de partida  "))
horaLlegada = int(input("Ingrese hora de llegada  "))
minutoLlegada = int(input("Ingrese minuto de llegada  "))
segundoLlegada = int(input("Ingrese segundo de llegada  "))
distancia = int(input("Ingrese distancia recorrida  "))
horario_partida = (horaPartida+minutoPartida/60+segundoPartida/3600)
horario_llegada = (horaLlegada+minutoLlegada/60+segundoLlegada/3600)
velocidad_promedio = str(distancia/(horario_llegada - horario_partida))
print("La velocidad promedio fue " + velocidad_promedio + " KM/h")
